name: conchayoro-pipeline
on:
   push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: ebconfig
        path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ebconfig
          path: .
      - run: |
          sed -i='' "s/<AWS_ACCOUNT_ID>/$AWS_ACCOUNT_ID/" Dockerrun.aws.json
          sed -i='' "s/<PROJECT_NAME>/$PROJECT_NAME/" Dockerrun.aws.json
          sed -i='' "s/<MODULE_NAME>/$MODULE_NAME/" Dockerrun.aws.json
          sed -i='' "s/<TAG>/$TAG/" Dockerrun.aws.json
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: |
          sudo apt-get update
          sudo apt-get install build-essential python3-dev libffi-dev libssl-dev
          pip install awsebcli
      - run: |
          eb deploy --verbose
