name: jobs examples
on:
  push
jobs:
  jobx:
   runs-on: ubuntu-latest
   steps:
   - name: configuração do node (pesquisar no marketplace...)
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: 16
